top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules
builddir     = /root/httpd-2.4.6/modules
VPATH        = /root/httpd-2.4.6/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

