top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/metadata
builddir     = /root/httpd-2.4.6/modules/metadata
VPATH        = /root/httpd-2.4.6/modules/metadata

include $(top_srcdir)/build/special.mk

