top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/proxy/balancers
builddir     = /root/httpd-2.4.6/modules/proxy/balancers
VPATH        = /root/httpd-2.4.6/modules/proxy/balancers
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
