top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/loggers
builddir     = /root/httpd-2.4.6/modules/loggers
VPATH        = /root/httpd-2.4.6/modules/loggers

include $(top_srcdir)/build/special.mk

