top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/generators
builddir     = /root/httpd-2.4.6/modules/generators
VPATH        = /root/httpd-2.4.6/modules/generators

include $(top_srcdir)/build/special.mk

