top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/echo
builddir     = /root/httpd-2.4.6/modules/echo
VPATH        = /root/httpd-2.4.6/modules/echo

include $(top_srcdir)/build/special.mk

