top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/aaa
builddir     = /root/httpd-2.4.6/modules/aaa
VPATH        = /root/httpd-2.4.6/modules/aaa

include $(top_srcdir)/build/special.mk

