top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/cache
builddir     = /root/httpd-2.4.6/modules/cache
VPATH        = /root/httpd-2.4.6/modules/cache

include $(top_srcdir)/build/special.mk

