top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/os
builddir     = /root/httpd-2.4.6/os
VPATH        = /root/httpd-2.4.6/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
