top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/arch/unix
builddir     = /root/httpd-2.4.6/modules/arch/unix
VPATH        = /root/httpd-2.4.6/modules/arch/unix

include $(top_srcdir)/build/special.mk

