top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/core
builddir     = /root/httpd-2.4.6/modules/core
VPATH        = /root/httpd-2.4.6/modules/core

include $(top_srcdir)/build/special.mk

