top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/modules/http
builddir     = /root/httpd-2.4.6/modules/http
VPATH        = /root/httpd-2.4.6/modules/http

include $(top_srcdir)/build/special.mk

