top_srcdir   = /root/httpd-2.4.6
top_builddir = /root/httpd-2.4.6
srcdir       = /root/httpd-2.4.6/server/mpm
builddir     = /root/httpd-2.4.6/server/mpm
VPATH        = /root/httpd-2.4.6/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
